### PR TITLE
cmd/mr_create: fix index out of range with --source

### LINKED ISSUE #699: Stack trace on wrong formatting of command
When using `lab mr create --source ...`, if the user uses non-expected formatting, lab explodes a stack trace.

```
$ lab mr create --source Some_RemoteSome_Branch
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/zaquestion/lab/cmd.runMRCreate(0x1961ae0, 0xc000502da0, 0x0, 0x2)
	/home/lzampier/Projects/forks/lab/cmd/mr_create.go:125 +0x204f
github.com/spf13/cobra.(*Command).execute(0x1961ae0, 0xc000502d80, 0x2, 0x2, 0x1961ae0, 0xc000502d80)
	/home/lzampier/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x195af40, 0xc00012c000, 0x5, 0x5)
	/home/lzampier/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/lzampier/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/zaquestion/lab/cmd.Execute(0xc000126b00)
	/home/lzampier/Projects/forks/lab/cmd/root.go:273 +0x3f9
main.main()
	/home/lzampier/Projects/forks/lab/main.go:27 +0x74
```
Note that on the example above, the command should've had a space between Some_Remote and Some_Branch.

It looks like some additional filtering is missing.

### PR DESCRIPTION
**Pull request by bmeneguele**
In case the user could use `lab mr create --source` with "remote" only,
without the branch part, or at least using `:` it would panic:

---- 8< ----
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/zaquestion/lab/cmd.runMRCreate(0x18f3600, 0xc00055a460, 0x0, 0x2)
        /home/bmeneg/git/lab/cmd/mr_create.go:125 +0x207e
github.com/spf13/cobra.(*Command).execute(0x18f3600, 0xc00055a440, 0x2, 0x2, 0x18f3600, 0xc00055a440)
        /home/bmeneg/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x18f8f40, 0xc00012a000, 0x5, 0x5)
        /home/bmeneg/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/bmeneg/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/zaquestion/lab/cmd.Execute(0xc000124100)
        /home/bmeneg/git/lab/cmd/root.go:273 +0x3c5
main.main()
        /home/bmeneg/git/lab/main.go:27 +0x74
---- >8 ----

This patch adds a condition to the number of elements after spliting the
string.

Fixes #699 

Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>

### CODE REVIEW

**Comment by prarit** [comment]
Oh good find :)

**Review by prarit — APPROVED** [review]

File: cmd/mr_create.go [hunk 1]
```diff
@@ -121,10 +121,13 @@ func runMRCreate(cmd *cobra.Command, args []string) {
...
 		sourceParts := strings.Split(sourceTarget, ":")
+		if len(sourceParts) < 2 {
+			log.Fatalf("source remote must have format remote:remote_branch")
+		}
 		sourceRemote = sourceParts[0]
 		sourceBranch = sourceParts[1]
 		if sourceRemote == "" || sourceBranch == "" {
-			log.Fatalf("source remote must have format remote:remote_branch.\n")
+			log.Fatalf("source remote must have format remote:remote_branch")
 		}
```
Comment (zampierilucas) [inline cmd/mr_create.go:131]: Is this check still valid? AFIK the problems that should've been catched here, are now being treated by lines 124:126, right?

Comment (bmeneguele) [reply cmd/mr_create.go:131]: It's still valid: if the user uses `--source whatever:` the `strings.Split(sourceTarget, ":")` returns a list of length of 2, being that the first value is `whatever` and the second one is an empty string. So we still need to make sure the user explicitly passed both `sourceRemote` and `sourceBranch`.

Comment (bmeneguele) [reply cmd/mr_create.go:131]: But yeah, I agree. Seems odd to have two similar checks one after the other. I spent some minutes trying to figure out if I was missing something.

Comment (zampierilucas) [reply cmd/mr_create.go:131]: Got it, I was misunderstanding the Split(), now it makes sense to me.

On the other hand, way to eliminate the one check would be to:
`if len(sourceParts) < 2  || sourceParts[0] == "" || sourceParts[1] == "" { `
But hey, I'm fine with how it is :)

**Review by zampierilucas — APPROVED** [review]

File: cmd/mr_create.go (hunk 1 above)
Comment (bmeneguele) [reply cmd/mr_create.go:131]: Yeah, that's right. Actually your suggestion gave me another thing to check.
I'm going to send a new version of the patch trimming all whitespaces.

**Comment by bmeneguele** [comment]
@prarit @zampierilucas I slightly changed the check, could you guys re-review?

**Review by zampierilucas — APPROVED** [review]
